Repository lumill925/CloneTeam2Backend, pull requests merged in 2022-08, with the labels that each got.

#5 Feature#4
  src/main/java/com/sparta/cloneteam2backend/CloneTeam2BackendApplication.java
  src/main/java/com/sparta/cloneteam2backend/controller/PostController.java
  src/main/java/com/sparta/cloneteam2backend/dto/ResponseDto.java
  src/main/java/com/sparta/cloneteam2backend/dto/post/PostRequestDto.java
  src/main/java/com/sparta/cloneteam2backend/dto/post/PostResponseDto.java
  src/main/java/com/sparta/cloneteam2backend/model/Category.java
  src/main/java/com/sparta/cloneteam2backend/model/Post.java
  src/main/java/com/sparta/cloneteam2backend/model/Timestamped.java
  src/main/java/com/sparta/cloneteam2backend/repository/PostRepository.java
  src/main/java/com/sparta/cloneteam2backend/service/PostService.java
Labels: enhancement

#8 이미지 업로드 및 리뷰 기능
  src/main/java/com/sparta/cloneteam2backend/config/AwsS3Config.java
  src/main/java/com/sparta/cloneteam2backend/controller/ReviewController.java
  src/main/java/com/sparta/cloneteam2backend/dto/review/ReviewRequestDto.java
  src/main/java/com/sparta/cloneteam2backend/dto/review/ReviewResponseDto.java
  src/main/java/com/sparta/cloneteam2backend/model/Img.java
  src/main/java/com/sparta/cloneteam2backend/model/Imgtarget.java
  src/main/java/com/sparta/cloneteam2backend/model/Review.java
  src/main/java/com/sparta/cloneteam2backend/repository/ImgRepository.java
  src/main/java/com/sparta/cloneteam2backend/repository/ReviewRepository.java
  src/main/java/com/sparta/cloneteam2backend/service/PostService.java
  src/main/java/com/sparta/cloneteam2backend/service/ReviewService.java
  src/main/java/com/sparta/cloneteam2backend/service/S3Service.java
Labels: enhancement

#10 이미지 수정 기능 추가
  build.gradle
  src/main/java/com/sparta/cloneteam2backend/repository/ImgRepository.java
  src/main/java/com/sparta/cloneteam2backend/service/S3Service.java
Labels: enhancement

#13 스웨거 추가
  build.gradle
  src/main/java/com/sparta/cloneteam2backend/config/SwaggerConfig.java
Labels: enhancement

#14 Feature#6
  build.gradle
  src/main/java/com/sparta/cloneteam2backend/config/SecurityConfig.java
  src/main/java/com/sparta/cloneteam2backend/controller/PostController.java
  src/main/java/com/sparta/cloneteam2backend/dto/facilities/FacilitiesRequestDto.java
  src/main/java/com/sparta/cloneteam2backend/dto/post/PostRequestDto.java
  src/main/java/com/sparta/cloneteam2backend/dto/post/PostResponseDto.java
  src/main/java/com/sparta/cloneteam2backend/model/Facilities.java
  src/main/java/com/sparta/cloneteam2backend/model/Post.java
  src/main/java/com/sparta/cloneteam2backend/repository/FacilitiesRepository.java
  src/main/java/com/sparta/cloneteam2backend/repository/ReviewRepository.java
  src/main/java/com/sparta/cloneteam2backend/service/FacilitiesService.java
  src/main/java/com/sparta/cloneteam2backend/service/PostService.java
Labels: enhancement

#17 Develop
  build.gradle
  src/main/java/com/sparta/cloneteam2backend/CloneTeam2BackendApplication.java
  src/main/java/com/sparta/cloneteam2backend/config/AwsS3Config.java
  src/main/java/com/sparta/cloneteam2backend/config/JwtSecurityConfig.java
  src/main/java/com/sparta/cloneteam2backend/config/SecurityConfig.java
  src/main/java/com/sparta/cloneteam2backend/config/SwaggerConfig.java
  src/main/java/com/sparta/cloneteam2backend/controller/AuthController.java
  src/main/java/com/sparta/cloneteam2backend/controller/PostController.java
  src/main/java/com/sparta/cloneteam2backend/controller/ReviewController.java
  src/main/java/com/sparta/cloneteam2backend/dto/Auth/AuthRequestDto.java
  src/main/java/com/sparta/cloneteam2backend/dto/Auth/AuthResponseDto.java
  src/main/java/com/sparta/cloneteam2backend/dto/Auth/TokenDto.java
  src/main/java/com/sparta/cloneteam2backend/dto/ResponseDto.java
  src/main/java/com/sparta/cloneteam2backend/dto/facilities/FacilitiesRequestDto.java
  src/main/java/com/sparta/cloneteam2backend/dto/post/PostRequestDto.java
  src/main/java/com/sparta/cloneteam2backend/dto/post/PostResponseDto.java
  src/main/java/com/sparta/cloneteam2backend/dto/review/ReviewRequestDto.java
  src/main/java/com/sparta/cloneteam2backend/dto/review/ReviewResponseDto.java
  src/main/java/com/sparta/cloneteam2backend/error/RestApiException.java
  src/main/java/com/sparta/cloneteam2backend/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/sparta/cloneteam2backend/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/sparta/cloneteam2backend/jwt/JwtFilter.java
  src/main/java/com/sparta/cloneteam2backend/jwt/TokenProvider.java
  src/main/java/com/sparta/cloneteam2backend/model/Authority.java
  src/main/java/com/sparta/cloneteam2backend/model/Category.java
  src/main/java/com/sparta/cloneteam2backend/model/Facilities.java
  src/main/java/com/sparta/cloneteam2backend/model/Img.java
  src/main/java/com/sparta/cloneteam2backend/model/Imgtarget.java
  src/main/java/com/sparta/cloneteam2backend/model/Post.java
  src/main/java/com/sparta/cloneteam2backend/model/RefreshToken.java
  src/main/java/com/sparta/cloneteam2backend/model/Review.java
  src/main/java/com/sparta/cloneteam2backend/model/Timestamped.java
  src/main/java/com/sparta/cloneteam2backend/model/User.java
  src/main/java/com/sparta/cloneteam2backend/repository/FacilitiesRepository.java
  src/main/java/com/sparta/cloneteam2backend/repository/ImgRepository.java
  src/main/java/com/sparta/cloneteam2backend/repository/PostRepository.java
  src/main/java/com/sparta/cloneteam2backend/repository/RefreshTokenRepository.java
  src/main/java/com/sparta/cloneteam2backend/repository/ReviewRepository.java
  src/main/java/com/sparta/cloneteam2backend/repository/UserRepository.java
  src/main/java/com/sparta/cloneteam2backend/service/AuthService.java
  src/main/java/com/sparta/cloneteam2backend/service/CustomUserDetailService.java
  src/main/java/com/sparta/cloneteam2backend/service/FacilitiesService.java
  src/main/java/com/sparta/cloneteam2backend/service/PostService.java
  src/main/java/com/sparta/cloneteam2backend/service/ReviewService.java
  src/main/java/com/sparta/cloneteam2backend/service/S3Service.java
Labels: enhancement

#18 Feature#15
  src/main/java/com/sparta/cloneteam2backend/controller/PostController.java
  src/main/java/com/sparta/cloneteam2backend/dto/facilities/FacilitiesRequestDto.java
  src/main/java/com/sparta/cloneteam2backend/dto/post/PostResponseDto.java
  src/main/java/com/sparta/cloneteam2backend/model/User.java
  src/main/java/com/sparta/cloneteam2backend/repository/FacilitiesRepository.java
  src/main/java/com/sparta/cloneteam2backend/service/FacilitiesService.java
  src/main/java/com/sparta/cloneteam2backend/service/PostService.java
Labels: enhancement

#21 [#19] bug: 포스트 상세조회시 편의시설부분 수정, 편의시설 입력 없을시 발생하는 에러 수정
  src/main/java/com/sparta/cloneteam2backend/controller/PostController.java
  src/main/java/com/sparta/cloneteam2backend/dto/post/PostRequestDto.java
  src/main/java/com/sparta/cloneteam2backend/model/Facilities.java
Labels: bug

#22 [#16] feat: 유저 정보, CORS 설정
  src/main/java/com/sparta/cloneteam2backend/config/SecurityConfig.java
  src/main/java/com/sparta/cloneteam2backend/controller/AuthController.java
  src/main/java/com/sparta/cloneteam2backend/controller/UserController.java
  src/main/java/com/sparta/cloneteam2backend/dto/user/AuthRequestDto.java
  src/main/java/com/sparta/cloneteam2backend/dto/user/AuthResponseDto.java
  src/main/java/com/sparta/cloneteam2backend/dto/user/TokenDto.java
  src/main/java/com/sparta/cloneteam2backend/error/RestApiException.java
  src/main/java/com/sparta/cloneteam2backend/jwt/TokenProvider.java
  src/main/java/com/sparta/cloneteam2backend/model/User.java
  src/main/java/com/sparta/cloneteam2backend/service/UserService.java
Labels: enhancement

#24 [#23] feat: 이미지 한글이름 에러 수정, .gitignore 수정
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/com/sparta/cloneteam2backend/service/S3Service.java
Labels: enhancement

#28 [#27] hotfix: Auth 관련 파일 삭제
  src/main/java/com/sparta/cloneteam2backend/controller/AuthController.java
  src/main/java/com/sparta/cloneteam2backend/dto/Auth/AuthRequestDto.java
  src/main/java/com/sparta/cloneteam2backend/dto/Auth/AuthResponseDto.java
  src/main/java/com/sparta/cloneteam2backend/dto/Auth/TokenDto.java
  src/main/java/com/sparta/cloneteam2backend/service/AuthService.java
Labels: bug

#31 Feature#29 user review mapping
  src/main/java/com/sparta/cloneteam2backend/controller/UserController.java
  src/main/java/com/sparta/cloneteam2backend/dto/review/ReviewRequestDto.java
  src/main/java/com/sparta/cloneteam2backend/dto/review/ReviewResponseDto.java
  src/main/java/com/sparta/cloneteam2backend/dto/user/UserRequestDto.java
  src/main/java/com/sparta/cloneteam2backend/dto/user/UserResponseDto.java
  src/main/java/com/sparta/cloneteam2backend/model/Review.java
  src/main/java/com/sparta/cloneteam2backend/model/User.java
  src/main/java/com/sparta/cloneteam2backend/service/ReviewService.java
  src/main/java/com/sparta/cloneteam2backend/service/UserService.java
Labels: enhancement

#34 Feature#33
  src/main/java/com/sparta/cloneteam2backend/controller/PostController.java
  src/main/java/com/sparta/cloneteam2backend/model/Category.java
  src/main/java/com/sparta/cloneteam2backend/model/Facilities.java
  src/main/java/com/sparta/cloneteam2backend/repository/PostRepository.java
  src/main/java/com/sparta/cloneteam2backend/service/PostService.java
Labels: enhancement

#37 develop 브랜치 자동배포 환경 설정
  .github/workflows/main.yml
  Procfile
  build.gradle
  src/main/resources/application-prod.yml
Labels: documentation
